db:
  DockerDSN: "postgres://user:password@postgres_container:5432/url_shortener"
  StandaloneDSN: "postgres://user:password@localhost:5432/url_shortener"
  maxOpenConns: 5
  maxIdleConns: 5
  connMaxIdleTime: 5m
  connMaxLifetime: 5m