version: "3.9"
services:
  app:
    build: .
    container_name: url-shortener-app
    depends_on:
      - postgres
    ports:
      - "8080:8080"
    networks:
      - app_network

  postgres:
    container_name: postgres_container
    image: postgres:17.2
    environment:
      POSTGRES_DB: url_shortener
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      PGDATA: "/var/lib/postgresql/data/pgdata"
    ports:
      - "5432:5432"
    restart: unless-stopped
    volumes:
      - pgdata:/var/lib/postgresql/data
    networks:
      - app_network

  pgadmin:
    container_name: pgadmin_container
    image: dpage/pgadmin4:7.2
    environment:
      PGADMIN_DEFAULT_EMAIL: "default@gmail.com"
      PGADMIN_DEFAULT_PASSWORD: "pgadmin"
      PGADMIN_CONFIG_SERVER_MODE: "False"
    volumes:
      - pgadmin-data:/var/lib/pgadmin
    ports:
      - "5050:80"
    restart: unless-stopped
    deploy:
      resources:
        limits:
          cpus: '0.5'
          memory: 1G
    networks:
      - app_network

volumes:
  pgdata:
  pgadmin-data:


networks:
  app_network:
    driver: bridge
